"""Generate the optional help pack and matching identifiers from one catalogue."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import struct
import zlib
from build_config import generate as generate_config, help_asset

ROOT = Path(__file__).resolve().parents[1]
HEADER = struct.Struct('<4sIHH')
ENTRY = struct.Struct('<HBBI')
# These IDs are a stable interface: runtime selectors use each contiguous group.
PAGE_IDS = tuple(f'{group}{i}' for group, count in
                 [('Hud', 2), ('Lesson', 4), ('Puzzle', 9), ('Medal', 15),
                  ('Debrief', 7), ('Mode', 15)] for i in range(count))


def encode(catalogue):
    names, pages = [], []
    for page in catalogue:
        name, lines = page['id'], page['lines']
        if not re.fullmatch(r'[A-Z][A-Za-z0-9]*', name) or name in names:
            raise ValueError('Invalid or duplicate help ID')
        if not 1 <= len(lines) <= 5 or any(not isinstance(line, str) or not line or
                                           any(ord(c) < 32 or ord(c) > 126 for c in line)
                                           for line in lines):
            raise ValueError('Help pages require one to five printable ASCII lines')
        data = b''.join(line.encode('ascii') + b'\0' for line in lines)
        if len(data) > 128:
            raise ValueError(f'{name}: help page exceeds 128 bytes')
        names.append(name)
        pages.append((data, len(lines)))
    if not names or len(names) >= 255:
        raise ValueError('Help ID space exhausted')
    if tuple(names) != PAGE_IDS:
        raise ValueError('Help IDs must retain their stable catalogue order')
    # Stable identity binds text, order, and IDs without depending on JSON whitespace.
    identity = int.from_bytes(hashlib.sha256(json.dumps(catalogue, sort_keys=True,
                                                       separators=(',', ':')).encode()).digest()[:4], 'little')
    offset = HEADER.size + ENTRY.size * len(pages)
    index, bodies = bytearray(), bytearray()
    for data, count in pages:
        index += ENTRY.pack(offset, len(data), count, zlib.crc32(data))
        bodies += data
        offset += len(data)
    if offset > 65535:
        raise ValueError('Help pack exceeds the offset range')
    packed = HEADER.pack(b'MCH1', identity, len(pages), ENTRY.size) + index + bodies
    header = ('// Generated by tools/help_assets.py; edit assets/help.json.\n#pragma once\n'
              f'#define MC_HELP_CATALOG_ID 0x{identity:08X}U\n'
              'enum {\n' + ''.join(f'    McHelp{name} = {i},\n' for i, name in enumerate(names)) +
              f'    McHelpPageCount = {len(names)},\n    McHelpNoPage = 255\n}};\n')
    return packed, header


def write_changed(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists() or path.read_bytes() != data:
        path.write_bytes(data)


def generate(root=ROOT):
    version = generate_config(root)
    packed, header = encode(json.loads((root / 'assets/help.json').read_text()))
    write_changed(root / 'build/generated/help_catalog.h', header.encode())
    write_changed(help_asset(root, version), packed)
    return packed


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()
    generate()
