// Compile the modules together so the device build can optimize across source-file boundaries
#include "binary.c" // core
#include "help_codec.c" // core
#include "help_storage.c" // ui
#include "help_ui.c" // ui
#include "app.c" // app
#include "collision.c" // core
#include "controls.c" // core
#include "feedback.c" // ui
#include "game.c" // core
#include "mode.c" // core
#include "storage_cleanup.c" // ui
#include "storage_worker.c" // ui
#include "persistence.c" // ui
#include "persistence_codec.c" // core
#include "render.c" // ui
#include "render_game.c" // ui
#include "render_screens.c" // ui
#include "ui_controller.c" // ui
#include "ui_menu.c" // ui
#include "wave.c" // core
